[package]
name = "freivald-scaffold"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.0"
rand = "0.8.5"

[dev-dependencies]
rstest = "0.12.0"
lazy_static = "1.4.0"
ndarray-rand = "0.14.0"

[profile.dev]
overflow-checks = false